syntax on
filetype on
au BufNewFile,BufRead *.cilk set filetype=cpp
colorschem desert 
set hlsearch
set et
set sw=2
set smarttab

" Jerome :
set autoindent
set expandtab
set softtabstop=2
set tabstop=2
set cindent
set nocp
filetype plugin on
filetype indent on
filetype plugin indent on

